show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
format_time: "%d-%m-%Y"
format_time_with_hour: "%d-%m-%Y, %H:%M:%S"
sort_descriptions: 75
foods:
  previous_week: 1
  precision_min: 0
unit_price: "vnđ"
percentage: 100
textarea:
  number_rows: 4
comments:
  limit: 3
  per_page: 3
day_only: "%d"
month_only: "%m"
year_only: "%Y"
user_avatar:
  medium: "300x300>"
  thumb: "100x100#"

status:
  new_order: 1
  in_progress: 2
  done: 3
user_type:
   admin: 2
   shipper: 1
   customer: 0
top_dashboard: 5
views:
  orders:
    order: "Order"
    